//@ ignore-cross-compile
// The debuginfo checks below read DWARF from the linked binary, which only works reliably
// on Linux (windows-msvc emits CodeView; macOS keeps DWARF in separate dSYM bundles).
//@ only-linux

// Regression test for stale debuginfo decl lines of macro-generated definitions.
//
// `MSTAT` is generated by a `#[collapse_debuginfo]` macro, so its `DW_AT_decl_line` renders
// the *invocation's* position, reached by walking the expansion chain to a call-site span
// that has no parent definition. `main_v1.rs` and `main_v2.rs` swap the equal-length
// invocation and padding lines, so the file's line table and every other byte offset are
// unchanged and only the invocation moves. `ExpnData`'s fingerprint deliberately ignores
// its spans' positions, so nothing re-fingerprints across this edit; the explicit
// `expn_anchor` dependency recorded when the walk lands on a parentless call
// site is the only thing that refreshes the reused object code's decl line.

use run_make_support::{llvm_dwarfdump, rfs, run, rustc};

fn main() {
    let build = || rustc().input("main.rs").incremental("incr").debuginfo("2").output("main").run();

    // `mk_stat! {}` sits on line 7 of `main_v1.rs` and line 8 of `main_v2.rs`.
    rfs::copy("main_v1.rs", "main.rs");
    build();
    run("main");
    llvm_dwarfdump()
        .input("main")
        .arg("--name=MSTAT")
        .run()
        .assert_stdout_contains_regex(r"DW_AT_decl_line\s*\(7\)");

    rfs::copy("main_v2.rs", "main.rs");
    build();
    run("main");
    llvm_dwarfdump()
        .input("main")
        .arg("--name=MSTAT")
        .run()
        .assert_stdout_contains_regex(r"DW_AT_decl_line\s*\(8\)");
}
